version: '3.9'

services:

  api:
    build: .
    container_name: backend_api

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/analytics_db

    restart: unless-stopped

  postgres:
    image: postgres:16

    container_name: backend_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: